### PR TITLE
Added implicit conversion to Result type, similar to the conversion that is being generated in OneOf

### PR DESCRIPTION
**Pull request by npcnixel**

### CODE REVIEW

**Comment by salvois** [comment]
Hi @CpnNixel ,
thanks for your contribution!
I'm not very accustomed to implicit conversions. Could you provide an example use case for your modification to help me better understand, please?
   Salvo

**Comment by npcnixel** [comment]
Hi @salvois!
Sure, so I have the next example.

```c#
    public async Task<Result<Success, NotFoundChargePointError>> Exists(string chargePointId)
    {
        return await chargePointRepository.GetByIdLight(chargePointId) is null
            ? Result.Error<Success, NotFoundChargePointError>(new NotFoundChargePointError(chargePointId))
            : Result.Ok<Success, NotFoundChargePointError>(new Success());
    }
```
Implicit conversion can help to simplify it

```c#
    public async Task<Result<Success, NotFoundChargePointError>> Exists(string chargePointId)
    {
        return await chargePointRepository.GetByIdLight(chargePointId) is null
            ? new NotFoundChargePointError(chargePointId)
            : new Success();
    }
```
Alias can help to simplify it down to

```c#
using SuccessOrNotFound = Result<Success, NotFoundChargePointError>;

  public async Task<SuccessOrNotFound> Exists(string chargePointId)
    {
        return await chargePointRepository.GetByIdLight(chargePointId) is null
            ? new NotFoundChargePointError(chargePointId)
            : new Success();
    }
```

**Comment by salvois** [comment]
Hi @CpnNixel ,
thanks for the example, now it's a little clearer to me.

To be honest, I still don't quite get the advantage of the implicit conversion. If I understand correctly, you can omit the named constructor when the type you are assigning to is know, like a parameter or an explicit variable declaration. Also, it would not work if T and TError are the same type, isn't it? If I remember correctly, this is an uninteresting use case for OneOf, but it's very possible with Result.

That may be just that I'm uncomfortable with implicit conversions (or implicit stuff) in general, so feel free to correct me if you see wider use cases!
Thanks,
   Salvo

**Comment by salvois** [comment]
Hi @CpnNixel ,
I ended up implementing something a little different than your pull request: named constructor to instantiate Result.Ok and Result.Error from a single argument, so that the compiler can deduce the type parameter.
In my opinion, this allows to stay explicit on your intent (creating a result type) while reducing "type noise", and also allows T and TError to be the same type if needed.
Hope you find it useful,
   Salvo

**Pull request closed without merging**
